logging: !include ../_include/logging/runtime_debug.yaml

providers:
  forex: !include ../_include/forex/oanda.yaml

agents:
- !include ../_include/importer_config/long.yaml

- !include ../_include/exporter/cgtcalculator_com/input.yaml